# Generated by Django 4.2.7 on 2025-08-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대'), ('60s', '60대 이상')], max_length=3, null=True, verbose_name='나이대'),
        ),
    ]
