# Generated by Django 5.2.5 on 2025-09-02 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대 이상', '60대 이상')], max_length=10)),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=10)),
                ('vacation_type', models.CharField(choices=[('해수욕, 물놀이', '해수욕, 물놀이'), ('등산, 캠핑', '등산, 캠핑'), ('문화생활', '문화생활'), ('도시 관광', '도시 관광'), ('휴양·힐링', '휴양·힐링'), ('맛집 투어', '맛집 투어'), ('친척·지인 방문', '친척·지인 방문'), ('기타', '기타')], max_length=20)),
                ('location_type', models.CharField(choices=[('국내', '국내'), ('해외', '해외')], max_length=10)),
                ('domestic_location', models.CharField(blank=True, max_length=20, null=True)),
                ('overseas_location', models.CharField(blank=True, max_length=20, null=True)),
                ('transportation', models.CharField(choices=[('자동차', '자동차'), ('버스', '버스'), ('기차', '기차'), ('항공편', '항공편'), ('배', '배'), ('도보', '도보')], max_length=20)),
                ('duration', models.CharField(choices=[('1일', '1일'), ('2~3일', '2~3일'), ('4~6일', '4~6일'), ('7~15일', '7~15일'), ('15일 이상', '15일 이상')], max_length=15)),
                ('companion', models.CharField(choices=[('혼자', '혼자'), ('가족', '가족'), ('친구', '친구'), ('연인', '연인'), ('직장 동료', '직장 동료'), ('동호회', '동호회'), ('기타', '기타')], max_length=20)),
                ('cost', models.CharField(choices=[('10만 원 이하', '10만 원 이하'), ('10만~30만 원', '10만~30만 원'), ('30만~50만 원', '30만~50만 원'), ('50만~100만 원', '50만~100만 원'), ('100만~200만 원', '100만~200만 원'), ('200만 원 이상', '200만 원 이상')], max_length=15)),
                ('satisfaction', models.IntegerField()),
                ('next_vacation_type', models.CharField(choices=[('해수욕, 물놀이', '해수욕, 물놀이'), ('등산, 캠핑', '등산, 캠핑'), ('문화생활', '문화생활'), ('도시 관광', '도시 관광'), ('휴양·힐링', '휴양·힐링'), ('맛집 투어', '맛집 투어'), ('친척·지인 방문', '친척·지인 방문'), ('기타', '기타')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
