# Generated by Django 4.2.7 on 2025-08-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대'), ('60s', '60대 이상')], max_length=3, verbose_name='연령대')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('vacation_type', models.CharField(choices=[('beach', '해수욕, 물놀이 (바다/섬 여행)'), ('outdoor', '등산, 캠핑 등 아웃도어 활동 (산/계곡 여행)'), ('culture', '문화생활 (전시, 공연, 역사 탐방, 축제 등)'), ('city', '도시 관광 (쇼핑, 카페, 시내 구경)'), ('healing', '휴양·힐링 (스파, 리조트, 펜션 휴식)'), ('food', '맛집 투어 (맛집 탐방, 지역 특산물 체험)'), ('visit', '친척·지인 방문'), ('other', '기타')], max_length=20, verbose_name='휴가 유형')),
                ('location_type', models.CharField(choices=[('domestic', '국내'), ('overseas', '해외')], max_length=10, verbose_name='위치 구분')),
                ('domestic_location', models.CharField(blank=True, choices=[('seoul', '서울'), ('busan', '부산'), ('daegu', '대구'), ('daejeon', '대전'), ('gwangju', '광주'), ('ulsan', '울산'), ('incheon', '인천'), ('sejong', '세종'), ('gangwon', '강원'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('jeonbuk', '전북'), ('jeonnam', '전남'), ('chungbuk', '충북'), ('chungnam', '충남'), ('jeju', '제주')], max_length=20, null=True, verbose_name='국내 지역')),
                ('overseas_location', models.CharField(blank=True, choices=[('east_asia', '동아시아'), ('southeast_asia', '동남아시아'), ('west_europe', '서유럽'), ('east_europe', '동유럽'), ('north_america', '북미'), ('south_america', '남미'), ('middle_east', '중동'), ('oceania', '오세아니아'), ('africa', '아프리카')], max_length=20, null=True, verbose_name='해외 지역')),
                ('transportation', models.CharField(choices=[('car', '자동차'), ('bus', '버스'), ('train', '기차'), ('airplane', '항공편'), ('ship', '배(선박)'), ('walk', '도보')], max_length=20, verbose_name='주요 교통수단')),
                ('duration', models.CharField(choices=[('1day', '1일'), ('2-3days', '2~3일'), ('4-6days', '4~6일'), ('7-15days', '7일~15일'), ('over15days', '15일 이상')], max_length=15, verbose_name='휴가 기간')),
                ('companion', models.CharField(choices=[('alone', '혼자'), ('family', '가족'), ('friends', '친구'), ('lover', '연인'), ('colleagues', '직장 동료'), ('club', '동호회'), ('other', '기타')], max_length=20, verbose_name='동행자')),
                ('cost', models.CharField(choices=[('under10', '10만 원 이하'), ('10-30', '10만~30만 원'), ('30-50', '30만~50만 원'), ('50-100', '50만~100만 원'), ('100-200', '100만~200만 원'), ('over200', '200만 원 이상')], max_length=15, verbose_name='총 비용')),
                ('satisfaction', models.IntegerField(choices=[(5, '매우 만족'), (4, '만족'), (3, '보통'), (2, '불만족'), (1, '매우 불만족')], verbose_name='만족도')),
                ('next_vacation_type', models.CharField(choices=[('beach', '바다/섬에서 물놀이'), ('outdoor', '산·계곡에서 아웃도어 활동'), ('culture', '전시·공연·축제 같은 문화 체험'), ('city', '도시 관광 및 쇼핑'), ('healing', '휴양·힐링 (스파, 리조트, 펜션 등)'), ('food', '맛집 탐방, 지역 특산물 체험'), ('visit', '친척·지인 방문'), ('other', '기타')], max_length=20, verbose_name='다음 휴가 희망 활동')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '여름휴가 설문조사',
                'verbose_name_plural': '여름휴가 설문조사들',
                'ordering': ['-created_at'],
            },
        ),
    ]
